# custom .travis.yml
# based on http://anil.recoil.org/2013/09/30/travis-and-ocaml.html

language: c
sudo: required
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-opam.sh
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docgen.sh

script:
  - PACKAGE="toml" TESTS=true bash -ex .travis-opam.sh
  - bash -ex .travis-docgen.sh

env:
  - OCAML_VERSION=4.01
  - OCAML_VERSION=4.02
  - OCAML_VERSION=4.03
  - OCAML_VERSION=4.04
os:
  - linux
  - osx

after_script:
  - opam install -y ocveralls
  - "`opam config var bin`/ocveralls _build/coverage*.out \
     --prefix _build \
     --send"

notifications:
  email: false

secure: "ZeEU8rPn/O7BFsPuFXhWAmuOGJaFZIIclgQkWrGiHFqWAxU6ivKWKotQ25ulhyMuHy1tx/QRrQBWFaGrYAFUWlz4DnGXhYKYE0H5slJCMWMS++mEHNHlQYrNQoTmApI2fTxDMPhm3L+JxEggi9iJaU2/u91wynu8jraxiL+X17w="
